version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: production
      APP_DEBUG: true
      APP_KEY: base64:qjtj5S8UiQKUMs6aDOzCWmxZbF2Q7W7voJAIx8xMX5I=
      APP_URL: https://backendlaravel.cupital.xyz
      DB_CONNECTION: mysql
      DB_HOST: 168.231.110.172
      DB_PORT: 8968
      DB_DATABASE: default
      DB_USERNAME: mysql
      DB_PASSWORD: NhUFwbcF6S7Noi7T1PvORJWM0J3FQCAhW7hOTvnmK5kbie1i9cnKNOcSH1juXokL
      JWT_SECRET: 
      JWT_TTL: 1440
      SESSION_DRIVER: database
      CACHE_STORE: database
      QUEUE_CONNECTION: database